import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'
import {ChangeEvent, useState} from 'react'
import {BsSearch} from 'react-icons/bs'
import SpinnerOld from "../../components/weatherold/SpinnerOld/SpinnerOld";
import {WeatherResponse} from "../../types/types";
import {NextPageWithLayout} from "../page";
import WeatherData from "../../components/weathher/WeatherData/WeatherData";

const Index: NextPageWithLayout = () => {

    const [city, setCity] = useState('');
    const [loading, setLoading] = useState(false);

    const [data, setData] = useState<WeatherResponse>();


    const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=metric&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`


    //  const getStaticProps: GetStaticProps = async (context) => {
    //     const res = await fetch(url);
    //     const { results }: GetWeatherResponse = await res.json();
    //
    //     return {
    //         props: {
    //             data : results,
    //         },
    //     };
    // }

    const fetchWeather = (e : any) => {
        e.preventDefault();
        setLoading(true);
        axios.get<WeatherResponse>(url).then((response) => {
            console.log(response.data);
            setData(response.data);
            })
        // setCity('');
        setLoading(false);
    };

    function handleChange(event: ChangeEvent<HTMLInputElement>) {
        console.log("handleChange occurs :" + event.target.value)
        setCity(event.target.value)
        console.log("city :" + city)
    }

    if (loading) {
        return <SpinnerOld />;
    } else {
        return (
            <div>
                <Head>
                    <title>Weather - Next App</title>
                    <meta name='description' content='Generated by create next app' />
                    <link rel='icon' href='/favicon.ico' />
                </Head>
                {/* Overlay */}
                <div className='absolute top-0 left-0 right-0 bottom-0 bg-black/40 z-[1]' />
                {/* Background image */}
                <Image
                    src='https://images.unsplash.com/photo-1513002749550-c59d786b8e6c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987&q=80'
                    layout='fill'
                    className='object-cover'
                />

                {/* Search */}
                <div className='relative flex justify-between items-center max-w-[500px] w-full m-auto pt-4 px-4 text-white z-10'>
                    <form
                        onSubmit={fetchWeather}
                        className='flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-300 text-white rounded-2xl'
                    >
                        <div>
                            <input
                                onChange={handleChange}
                                className='bg-transparent border-none text-white focus:outline-none text-2xl'
                                type='text'
                                placeholder='Search city'
                            />
                        </div>
                        <button onClick={fetchWeather}>
                            <BsSearch size={20} />
                        </button>
                    </form>
                </div>

                {/* Weather */}
                {data?.main && <WeatherData data={data} />}
            </div>
        );
    }
}

export default Index;

// <button onClick={fetchWeather}>Fetch data</button>
// https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={API key}
// https://api.openweathermap.org/data/2.5/weather?q={city name}&appid={API key}
